INSERT countries (code, name, phone_code) VALUES  ('ZA', 'South Africa', '+27');
INSERT countries (code, name, phone_code) VALUES  ('IE', 'Ireland', '+353');
INSERT countries (code, name, phone_code) VALUES  ('GA', 'Gabon', '+241');
INSERT countries (code, name, phone_code) VALUES  ('NO',  'Norway', '+47');
INSERT countries (code, name, phone_code) VALUES  ('IN',  'India', '+91');
INSERT countries (code, name, phone_code) VALUES  ('ZM',  'Zambia', '+260');
INSERT countries (code, name, phone_code) VALUES  ('KE',  'Kenya', '+254');
INSERT countries (code, name, phone_code) VALUES  ('PL', 'Poland', '+48');
INSERT countries (code, name, phone_code) VALUES  ('UG', 'Uganda', '+256');
INSERT countries (code, name, phone_code) VALUES  ('EE', 'Estonia' ,'+372');
INSERT countries (code, name, phone_code) VALUES  ('FR', 'France', '+33');
INSERT countries (code, name, phone_code) VALUES  ('TZ', 'Tanzania', '+255');
INSERT countries (code, name, phone_code) VALUES  ('GB', 'United Kingdom', '+44');
INSERT countries (code, name, phone_code) VALUES  ('DE', 'Germany', '+49');
INSERT countries (code, name, phone_code) VALUES  ('CI', 'Ivory Coast', '+225');
INSERT countries (code, name, phone_code) VALUES  ('BJ', 'Benin', '+229');
INSERT countries (code, name, phone_code) VALUES  ('LT', 'Lithuania', '+370');
INSERT countries (code, name, phone_code) VALUES  ('CA', 'Canada', '+1');
INSERT countries (code, name, phone_code) VALUES  ('ES', 'Spain', '+34');
INSERT countries (code, name, phone_code) VALUES  ('LV', 'Latvia', '+371');
INSERT countries (code, name, phone_code) VALUES  ('ET', 'Ethiopia', '+251');
INSERT countries (code, name, phone_code) VALUES  ('PT', 'Portugal', '+351');
INSERT countries (code, name, phone_code) VALUES  ('RW', 'Rwanda', '+250');
INSERT countries (code, name, phone_code) VALUES  ('GH', 'Ghana', '+233');
INSERT countries (code, name, phone_code) VALUES  ('NG', 'Nigeria', '+234');
INSERT countries (code, name, phone_code) VALUES  ('SE', 'Sweden', '+46');
INSERT countries (code, name, phone_code) VALUES  ('IT', 'Italy', '+39');
INSERT countries (code, name, phone_code) VALUES  ('DK', 'Denmark', '+45');
INSERT countries (code, name, phone_code) VALUES  ('NL', 'Netherlands', '+31');
INSERT countries (code, name, phone_code) VALUES  ('SL', 'Sierra Leone', '+232');
INSERT countries (code, name, phone_code) VALUES  ('US', 'United States of America', '+1');
